config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: 'blog/posts#index'

  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
       resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end

  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: :slugged

	belongs_to :author#, :optional => true

	scope :most_recent, -> { order(id: :desc) }

	def should_generate_new_friendly_id?
		title_changed?
	end

	def published_date
		created_at.strftime('%-d %-b, %Y')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	layout 'author'
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
	before_action :authenticate_author!
end

app/controllers/authors/posts_controller.rb
module Authors
	class PostsController < AuthorController
	  before_action :set_post, only: [:show, :edit, :update, :destroy]

	  # GET /posts
	  # GET /posts.json
	  def index
	  	# puts current_author
	    @posts = current_author.posts.most_recent
	  end

	  # GET /posts/1
	  # GET /posts/1.json
	  def show
	  end

	  # GET /posts/new
	  def new
	    @post = current_author.posts.new
	  end

	  # GET /posts/1/edit
	  def edit
	  end

	  # POST /posts
	  # POST /posts.json
	  def create
	    @post = current_author.posts.new(post_params)
	    puts @post

	    respond_to do |format|
	      if @post.save
	        format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
	        format.json { render :show, status: :created, location: @post }
	      else
	        format.html { render :new }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # PATCH/PUT /posts/1
	  # PATCH/PUT /posts/1.json
	  def update
	    respond_to do |format|
	      if @post.update(post_params)
	        format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
	        format.json { render :show, status: :ok, location: @post }
	      else
	        format.html { render :edit }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # DELETE /posts/1
	  # DELETE /posts/1.json
	  def destroy
	    @post.destroy
	    respond_to do |format|
	      format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	  end

	  private
	    # Use callbacks to share common setup or constraints between actions.
	    def set_post
	      @post = current_author.posts.friendly.find(params[:id])
	    end

	    # Never trust parameters from the scary internet, only allow the white list through.
	    def post_params
	      params.require(:post).permit(:title, :body, :description, :banner_image_url)
	    end
	end
end

app/controllers/blog/pages_controller.rb
module Blog
	class PagesController < BlogController
		def about
		end
		def contact
		end
	end
end

app/controllers/blog/posts_controller.rb
module Blog
	class PostsController < BlogController
	 # before_action :set_post, only: [:show, :edit, :update, :destroy]

	  # GET /posts
	  # GET /posts.json
	  def index
	    @posts = Post.most_recent
	  end

	  # GET /posts/1
	  # GET /posts/1.json
	  def show
	  		      @post = Post.friendly.find(params[:id])

	  end
	end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_with(model: post, url: url, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md">
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>

      <div class="field">
        <%= form.label :banner_image_url %>
        <%= form.text_field :banner_image_url %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description %>
      </div>
    </div>
    <div class="col-md-9">
      <div class="field">
        <%= form.label :body %>
        <%= form.text_area :body %>
      </div>
    </div>
  </div>

  

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/posts/_post.html.erb
<tr>
	<td><%= link_to post.title, authors_post_path(post) %></td>
	<td></td>
	<td><%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning'%></td>
	<td><%= link_to 'Remove', authors_post_path(post), method: :delete, data: {confirm: 'You sure mate?' }, class: 'btn btn-sm btn-danger'%></td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Edit #{@post.title}") %>
<% provide(:author, 'active') %>


<h1>Editing Post!</h1>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', authors_posts_path %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:author, 'active') %>


<div class="row">
	<div>
		<%= link_to 'New Post', new_authors_post_path, class: 'btn btn-primary btn-lg'%>
	</div>
	<br>
	<table class="table table-striped">
		<tr>
			<th colspan="4">Title</th>
		</tr>
	
    	<%= render @posts %>
	</table>   
  

</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:author, 'active') %>



<h1>New Post</h1>

<%= render 'form', post: @post, url: authors_posts_url %>

<%= link_to 'Back', authors_posts_path %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:author, 'active') %>

<div>
	<%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning'%>
	<%= link_to 'Remove', authors_post_path(@post), method: :delete, data: {confirm: 'You sure mate?' }, class: 'btn btn-sm btn-danger'%>
</div>

<div class="row">
  <div class='col-md-10 offset-md-1 col-lg-8 offset-lf-2 text-xs-center'>
  	<div style='background-image: url(<%= @post.banner_image_url %>)'>
  		<h1><%= @post.title %></h1>
  	</div>
  	<p> Published <%= @post.published_date %></p>
  	<%= @post.body.html_safe %>
  </div>
</div>

app/views/blog/pages/about.html.erb
<% provide(:about_active, 'active') %>

<h1> About Page </h1>

app/views/blog/pages/contact.html.erb
<% provide(:contact_active, 'active') %>
<h1> Contact Us </h1>

app/views/blog/posts/_post.html.erb
<div class='col-sm-6 col-sm-4'>
	<div class="card">
		<div class="card-topper" style='background-image: url(<%= post.banner_image_url %>)'></div>
		<div class="card-block">
			<h4 class="card-title"><%= link_to post.title, post %></h4>
			<p class="published-date"> Published <%= post.published_date %> </p>
			<p class="card-text"><%= truncate(post.description, length: 130) %></p>
			<%= link_to 'Read', post_path(post), class: 'btn btn-outline-secondary' %>
		</div>
	</div>
</div>

app/views/blog/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:blog_active, 'active') %>


<div class="row">
  <% @posts.each do |post| %>
    <%= render post %>
  <%end%>

</div>

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>



<div class="row">
  <div class='col-md-10 offset-md-1 col-lg-8 offset-lf-2 text-xs-center'>
  	<div style='background-image: url(<%= @post.banner_image_url %>)'>
  		<h1><%= @post.title %></h1>
  	</div>
  	<p> Published <%= @post.published_date %></p>
  	<%= @post.body.html_safe %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light style="backgroung-color: #1254;">
  <a class="navbar-brand" href="/">LUND</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
       <li class="nav-item">
        <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
      </li>
      <% if author_signed_in? %>
        <li class="nav-item">
          <%= link_to 'My Posts', authors_posts_path, class: "nav-link #{yield(:author_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
    
  </body>
</html>